# Generated by Django 4.2.16 on 2024-10-25 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_activity_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modules',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_id_modules', to='UserServices.modules'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_id_user_permissions', to='UserServices.modules'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usershippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_user_shipping_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
