# Generated by Django 5.1.2 on 2024-10-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0002_alter_activitylog_user_alter_modules_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
