# Generated by Django 5.1.2 on 2024-10-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
