# Generated by Django 5.1.1 on 2024-11-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User'), ('Vendor', 'Vendor'), ('Customer', 'Customer'), ('Super Admin', 'Super Admin')], max_length=50, null=True),
        ),
    ]
