# Generated by Django 4.2.16 on 2024-10-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('mrp', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percentage', 'Percentage')], default='Percentage', max_length=255, null=True)),
                ('discount_amount', models.FloatField()),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturing_date', models.DateTimeField(blank=True, null=True)),
                ('unit_of_measurement', models.CharField(max_length=255)),
                ('ptr', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_inwarded', models.IntegerField()),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_status', models.CharField(blank=True, choices=[('In_Stock', 'In_Stock'), ('Out_Of_Stock', 'Out_Of_Stock')], default='In_Stock', max_length=255, null=True)),
                ('inward_type', models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Return', 'Return'), ('Replacement', 'Replacement'), ('Warehouse Transfer', 'Warehouse Transfer')], default='Purchase', max_length=255, null=True)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('Inward', 'Inward'), ('Outward', 'Outward'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Expired', 'Expired'), ('Returned', 'Returned'), ('Adjustment', 'Adjustment'), ('Warehouse Transfer', 'Warehouse Transfer')], default='In_Stock', max_length=255, null=True)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackAndShelvesAndFloor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rack', models.CharField(max_length=255)),
                ('shelf', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=255)),
                ('capacity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=255)),
                ('warehouse_type', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented')], default='Owned', max_length=255)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
